//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobArea
    {
        public JobArea()
        {
            this.JobPostings = new HashSet<JobPosting>();
        }
    
        public int JobAreaId { get; set; }
        public string JAName { get; set; }
    
        public virtual ICollection<JobPosting> JobPostings { get; set; }
    }
}
