//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string VerCode { get; set; }
        public string isVerified { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
        public virtual Company Company { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
